-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 13:00:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Adocao_legal` DEFAULT CHARACTER SET utf8 ;
USE `Adocao_legal` ;

-- -----------------------------------------------------
-- Table `mydb`.`pré_requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`pré_requisito` (
  `idpré_requisito` INT NOT NULL,
  `fomulario` VARCHAR(45) NULL,
  PRIMARY KEY (`idpré_requisito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endreço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`endreço` (
  `idendreço` INT NOT NULL,
  `endereço` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `país` VARCHAR(45) NULL,
  PRIMARY KEY (`idendreço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`usuario` (
  `idusuario` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`pessoa` (
  `idpessoa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `dataNasc` DATE NULL,
  `e-mail` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  `pré_requisito_idpré_requisito` INT NOT NULL,
  `endreço_idendreço` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idpessoa`, `pré_requisito_idpré_requisito`, `endreço_idendreço`, `usuario_idusuario`),
  INDEX `fk__pré_requisito_idx` (`pré_requisito_idpré_requisito` ASC),
  INDEX `fk_pessoa_endreço1_idx` (`endreço_idendreço` ASC),
  INDEX `fk_pessoa_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk__pré_requisito`
    FOREIGN KEY (`pré_requisito_idpré_requisito`)
    REFERENCES `Adocao_legal`.`pré_requisito` (`idpré_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_endreço1`
    FOREIGN KEY (`endreço_idendreço`)
    REFERENCES `Adocao_legal`.`endreço` (`idendreço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `Adocao_legal`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paraDoar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`paraDoar` (
  `idparaDoar` INT NOT NULL,
  `nome_animal` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  `data_entrada` DATE NULL,
  `tempo` VARCHAR(45) NULL,
  `pré_requisito_idpré_requisito` INT NOT NULL,
  PRIMARY KEY (`idparaDoar`, `pré_requisito_idpré_requisito`),
  INDEX `fk_paraDoar_pré_requisito1_idx` (`pré_requisito_idpré_requisito` ASC),
  CONSTRAINT `fk_paraDoar_pré_requisito1`
    FOREIGN KEY (`pré_requisito_idpré_requisito`)
    REFERENCES `Adocao_legal`.`pré_requisito` (`idpré_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`animal` (
  `idanimal` INT NOT NULL,
  `racça` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `dataNasc` INT NULL,
  `dono` VARCHAR(45) NULL,
  `animalcol` VARCHAR(45) NULL,
  `pessoa_idpessoa` INT NOT NULL,
  `pessoa_pré_requisito_idpré_requisito` INT NOT NULL,
  `pessoa_endreço_idendreço` INT NOT NULL,
  `paraDoar_idparaDoar` INT NOT NULL,
  `paraDoar_pré_requisito_idpré_requisito` INT NOT NULL,
  PRIMARY KEY (`idanimal`, `pessoa_idpessoa`, `pessoa_pré_requisito_idpré_requisito`, `pessoa_endreço_idendreço`, `paraDoar_idparaDoar`, `paraDoar_pré_requisito_idpré_requisito`),
  INDEX `fk_animal_pessoa1_idx` (`pessoa_idpessoa` ASC, `pessoa_pré_requisito_idpré_requisito` ASC, `pessoa_endreço_idendreço` ASC),
  INDEX `fk_animal_paraDoar1_idx` (`paraDoar_idparaDoar` ASC, `paraDoar_pré_requisito_idpré_requisito` ASC),
  CONSTRAINT `fk_animal_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa` , `pessoa_pré_requisito_idpré_requisito` , `pessoa_endreço_idendreço`)
    REFERENCES `Adocao_legal`.`pessoa` (`idpessoa` , `pré_requisito_idpré_requisito` , `endreço_idendreço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_paraDoar1`
    FOREIGN KEY (`paraDoar_idparaDoar` , `paraDoar_pré_requisito_idpré_requisito`)
    REFERENCES `Adocao_legal`.`paraDoar` (`idparaDoar` , `pré_requisito_idpré_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao_legal`.`telefone` (
  `id` INT NOT NULL,
  `ddd` INT NULL,
  `telefone1` INT NULL,
  `telefone2` INT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  `pessoa_pré_requisito_idpré_requisito` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoa_idpessoa`, `pessoa_pré_requisito_idpré_requisito`),
  INDEX `fk_telefone_pessoa1_idx` (`pessoa_idpessoa` ASC, `pessoa_pré_requisito_idpré_requisito` ASC),
  CONSTRAINT `fk_telefone_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa` , `pessoa_pré_requisito_idpré_requisito`)
    REFERENCES `Adocao_legal`.`pessoa` (`idpessoa` , `pré_requisito_idpré_requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
